FROM node:14 AS ui-build

WORKDIR /client/
COPY /client/package.json ./
COPY /client/package-lock.json ./
RUN npm install
COPY /client/src/ ./src
COPY /client/public/ ./public
RUN npm run build

FROM node:14 AS server-build

WORKDIR /
COPY --from=ui-build /client/build/ ./client/build/
WORKDIR /server/

COPY /server/package.json ./
COPY /server/package-lock.json ./
RUN npm install

COPY /server/bin/ ./bin
COPY /server/config/ ./config
COPY /server/db/ ./db
COPY /server/routes/ ./routes
COPY /server/utils/ ./utils
COPY /server/.sequelizerc ./server
COPY /server/app.js ./server
COPY /server/demoSSbase64.js ./server
COPY /server/.env ./server

ENV NODE_ENV=development

EXPOSE 5000

CMD [ "node", "app.js" ]
